### PR TITLE
Simplify android check

### PR DESCRIPTION
**Pull request by hannesa2**
It simplify this version check.
For me graphic memory consumption works on Pixel 4 and click hotspot works for Emulator and Pixel 4

Please @mupm1 give it a try

### CODE REVIEW

**Comment by hannesa2** [comment]
Now I do stuff with Kotlin extension functions

**Comment by mupm1** [comment]
@hannesa2 please revert to 1.8.0 and just change version getter method then release new version

**Comment by mupm1** [comment]
please download this aar file of panorama and test on your device.

https://ufile.io/irq5ub31

**Comment by hannesa2** [comment]
> @hannesa2 please download this aar file of panorama and test on your device.
> 
> https://ufile.io/irq5ub31

There is no need, I added your repo as remote and build it by my own. 
Now I do rebase commit-by-commit

**Comment by hannesa2** [comment]
YES !
With this branch, I increased the loop to 400 and observed on step ~150 this
image

But next 4 tries there were no memory cleanup 🤔
The main problem is a memory crash ? I did a loop over 1200 and I **NEVER** had any memory problems on my Pixel4
For me it's close to a ghost hunt.

**Comment by hannesa2** [comment]
This one doesn't work and I'll close it.
Maybe I improve it later

**Pull request closed without merging**
